name: Validate with Hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    name: Run Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: franklin_wh
      - uses: home-assistant/actions/hassfest@master
